# Generated by Django 4.2.7 on 2024-01-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about",
            field=models.TextField(default="Hi! I am new to Winston's Archive."),
        ),
    ]
