# Generated by Django 4.2.7 on 2024-02-04 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_about"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bg_image",
        ),
    ]
