# Generated by Django 4.2.7 on 2024-01-21 23:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_tag_alter_comment_body_alter_post_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.AddField(
            model_name="post",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
